database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  name: "blog"

redis:
  host: "localhost"
  port: 6379
  password: ""

server:
  port: "8080"
  debug: true

JWT:
  Secret: "my-secret-key"

Page:
  Size: "10"